# Generated by Django 4.0.3 on 2022-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForUserReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('full_adress', models.CharField(max_length=400)),
                ('phone_num', models.CharField(max_length=20)),
                ('summa', models.CharField(max_length=100)),
            ],
        ),
    ]
